[package]
name = "fri"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0"
sha3 = "0.10.8"
fiat_shamir = { path = "../fiat_shamir" }
polynomials = { path = "../polynomials" }
fft = { path = "../fft" }
ark-bn254 = "0.5.0"
ark-bls12-377 = "0.5.0"

