[package]
name = "sumcheck"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
polynomials = { path = "../polynomials" }
fiat_shamir = { path = "../fiat_shamir" }
field-tracker = { git = "https://github.com/sublinearlabs/field-tracker/" }